#!/bin/bash

script_dir=$(dirname "$(readlink -f "$0")")
source "$script_dir/lib.sh"

cd "$GRIM_DAWN_SAVE_DIR"
cat .current-stash 2>/dev/null
find _stashes/ -type f -name '*.gst' | sed -r -e 's#^_stashes/##' | sed -r -e 's#\.gst$##' | sort
